# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_CACHE_DSN)%'
    secret: '%env(APP_SECRET)%'
    session: true
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
