services:
    php:
        build: .
        container_name: php
        depends_on:
            - mysql
            - redis
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
    redis:
        image: redis:7
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    mysql:
        image: mysql:8.0.32
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
    redis_data:
