version: "3.9"

services:
    redis:
        image: redis:7
        container_name: redis-cache
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            -   redis_data:/data
    database:
        image: mysql:8.0.32
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
    redis_data:
